@startuml
left to right direction
'actor
actor Penguji
actor Programmer

'case
usecase "Mendeteksi\nketersediaan spesifikasi" as (SKPL-GG-01)
usecase "Mendeteksi kesesuaian\nhasil compiler" as (SKPL-GG-02)
usecase "Mendeteksi\nplagiat kode sumber" as (SKPL-GG-03)

usecase "Penilaian terhadap\nkode sumber" as (SKPL-MP-01)
usecase "Memanipulasi score" as (SKPL-MP-01-01)
usecase "Hasil pemeriksaan library\ngrading-genius" as (SKPL-MP-01-02)
usecase "Membaca file\nkode sumber" as (SKPL-MP-01-03)
usecase "Mengecek kesesuaian\nspesifikasi" as (SKPL-MP-01-04)
usecase "Hitung penilaian dari\nhasil pemeriksaan\ndengan score" as (SKPL-MP-01-05)
usecase "Memeriksa plagiat kode sumber" as (SKPL-MP-01-06)
usecase "Mengambil penilaian secara\nlangsung dari kode sumber" as (SKPL-MP-01-07)

usecase "Rancangan REST API dan WEB" as (SKPL-MP-02)
usecase "Middleware saat melakukan logging" as (SKPL-MP-02-01)
usecase "Mengambil semua data\npenilaian hasil evaluasi" as (SKPL-MP-02-02)
usecase "Mengambil data penilaian\nhasil evaluasi berdasarkan\nnama file" as (SKPL-MP-02-03)
usecase "Mengupload file JavaScript" as (SKPL-MP-02-04)
usecase "Mengubah nilai score" as (SKPL-MP-02-05)

Penguji -> (SKPL-MP-01)
(SKPL-MP-01-01) ..> (SKPL-MP-01) : <<extend>>
(SKPL-MP-01) ..> (SKPL-MP-01-02) : <<include>>

(SKPL-MP-01-02) ..> (SKPL-GG-01) : <<include>>
(SKPL-MP-01-02) ..> (SKPL-GG-02) : <<include>>
(SKPL-MP-01-02) ..> (SKPL-GG-03) : <<include>>

(SKPL-MP-01) ..> (SKPL-MP-01-03) : <<include>>
(SKPL-MP-01) ..> (SKPL-MP-01-04) : <<include>>
(SKPL-MP-01) ..> (SKPL-MP-01-05) : <<include>>
(SKPL-MP-01) ..> (SKPL-MP-01-06) : <<include>>
(SKPL-MP-01) ..> (SKPL-MP-01-07) : <<include>>

Penguji -> (SKPL-MP-02)
(SKPL-MP-02) ..> (SKPL-MP-02-01) : <<include>>
(SKPL-MP-02-02) ..> (SKPL-MP-02) : <<extend>>
(SKPL-MP-02-03) ..> (SKPL-MP-02) : <<extend>>
(SKPL-MP-02) ..> (SKPL-MP-02-04) : <<include>>
(SKPL-MP-02-05) ..> (SKPL-MP-02) : <<extend>>

Programmer --> (SKPL-MP-02-03)
Programmer --> (SKPL-MP-02-04)
@enduml
