@startuml
actor "Penguji/Programmer"
participant Sistem

"Penguji/Programmer" -> Sistem: Mengakses sistem
"Penguji/Programmer" -> Sistem: Memilih opsi untuk merancang REST API dan WEB
Sistem -> Sistem: Melakukan perancangan
alt Mampu melakukan pada use case ID (SKPL-MP-02-01)
    Sistem -> Sistem: Middleware saat melakukan logging
end
alt Mampu melakukan pada use case ID (SKPL-MP-02-02)
    Sistem -> Sistem: Mengambil semua data penilaian hasil evaluasi
end
alt Mampu melakukan pada use case ID (SKPL-MP-02-03)
    Sistem -> Sistem: Mengambil data penilaian hasil evaluasi berdasarkan nama file
end
alt Mampu melakukan pada use case ID (SKPL-MP-02-04)
    Sistem -> Sistem: Mengupload file JavaScript
end
alt Mampu melakukan pada use case ID (SKPL-MP-02-05)
    Sistem -> Sistem: Mengubah nilai score
end
alt REST API atau WEB dapat digunakan
    Sistem -> "Penguji/Programmer": Tampilkan hasil perancangan
else
    Sistem -> "Penguji/Programmer": Tampilkan pesan kesalahan
end
@enduml
