@startuml
actor Penguji
participant Sistem

Penguji -> Sistem: Mengakses sistem
Penguji -> Sistem: Memilih opsi untuk mendeteksi plagiat
Sistem -> Sistem: Ubah semua kode sumber ke buffer
Sistem -> Sistem: Periksa plagiat kode sumber
alt Data pemeriksaan spesifikasi kosong
    Sistem -> Penguji: Tampilkan pesan kesalahan
else
    Sistem -> Penguji: Tampilkan hasil pemeriksaan plagiat
end
@enduml
