@startuml
|Main Project|
start
:Mengubah file kode sumber menjadi buffer;
|Grading Genius|
:Mengambil hasil evaluasi dengan library grading genius;
|Main Project|
:Mengecek kesesuaian spesifikasi;
if (Sama dengan spesifikasi penguji) then (yes)
    :Mendapatkan point;
else (no)
    :Tidak mendapatkan point;
endif
:Menghitung penilaian sepesifikasi dengan point;
:Mendapatkan hasil evaluasi yang didapatkan dari penilaian kode sumber;
stop
@enduml
